In [11]:
import pandas as pd
import math
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
#Load dataset
irisDataset = pd.read_csv("iris.csv", sep=',', skiprows=0)
irisDataset

Id  Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)  \
0      1                5.1               3.5                1.4   
1      2                4.9               3.0                1.4   
2      3                4.7               3.2                1.3   
3      4                4.6               3.1                1.5   
4      5                5.0               3.6                1.4   
..   ...                ...               ...                ...   
145  146                6.7               3.0                5.2   
146  147                6.3               2.5                5.0   
147  148                6.5               3.0                5.2   
148  149                6.2               3.4                5.4   
149  150                5.9               3.0                5.1   

     Petal Width (cm)         Species  
0                 0.2     Iris-setosa  
1                 0.2     Iris-setosa  
2                 0.2     Iris-setosa  
3                 0.2     Iris-setosa  
4                 0.2     Iris-setosa  
..                ...             ...  
145               2.3  Iris-virginica  
146               1.9  Iris-virginica  
147               2.0  Iris-virginica  
148               2.3  Iris-virginica  
149               1.8  Iris-virginica  

[150 rows x 6 columns]

In [16]:
#Memisahkan atribut dengan target class
X = irisDataset.iloc[:, 1:6].values
y = irisDataset['Species'].values
print("Atribut Dataset :")
print(X)
print("Class Target Dataset :")
print(y)

Atribut Dataset :
[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.4 3.9 1.7 0.4 'Iris-setosa']
 [4.6 3.4 1.4 0.3 'Iris-setosa']
 [5.0 3.4 1.5 0.2 'Iris-setosa']
 [4.4 2.9 1.4 0.2 'Iris-setosa']
 [4.9 3.1 1.5 0.1 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.8 3.0 1.4 0.1 'Iris-setosa']
 [4.3 3.0 1.1 0.1 'Iris-setosa']
 [5.8 4.0 1.2 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.1 3.5 1.4 0.3 'Iris-setosa']
 [5.7 3.8 1.7 0.3 'Iris-setosa']
 [5.1 3.8 1.5 0.3 'Iris-setosa']
 [5.4 3.4 1.7 0.2 'Iris-setosa']
 [5.1 3.7 1.5 0.4 'Iris-setosa']
 [4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.1 3.3 1.7 0.5 'Iris-setosa']
 [4.8 3.4 1.9 0.2 'Iris-setosa']
 [5.0 3.0 1.6 0.2 'Iris-setosa']
 [5.0 3.4 1.6 0.4 'Iris-setosa']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.6 0.2 'Iris-s

In [37]:
#spliting data training dan data testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Data Training : ")
print(X_train)
print(len(X_train))
print("Label Data Training : ")
print(y_train)
print(len(y_train))
print("Data Testing : ")
print(X_test)
print(len(X_test))
print("Label Data Testing : ")
print(y_test)
print(len(y_test))

Data Training : 
[[4.6 3.6 1.0 0.2 'Iris-setosa']
 [5.7 4.4 1.5 0.4 'Iris-setosa']
 [6.7 3.1 4.4 1.4 'Iris-versicolor']
 [4.8 3.4 1.6 0.2 'Iris-setosa']
 [4.4 3.2 1.3 0.2 'Iris-setosa']
 [6.3 2.5 5.0 1.9 'Iris-virginica']
 [6.4 3.2 4.5 1.5 'Iris-versicolor']
 [5.2 3.5 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']
 [5.2 4.1 1.5 0.1 'Iris-setosa']
 [5.8 2.7 5.1 1.9 'Iris-virginica']
 [6.0 3.4 4.5 1.6 'Iris-versicolor']
 [6.7 3.1 4.7 1.5 'Iris-versicolor']
 [5.4 3.9 1.3 0.4 'Iris-setosa']
 [5.4 3.7 1.5 0.2 'Iris-setosa']
 [5.5 2.4 3.7 1.0 'Iris-versicolor']
 [6.3 2.8 5.1 1.5 'Iris-virginica']
 [6.4 3.1 5.5 1.8 'Iris-virginica']
 [6.6 3.0 4.4 1.4 'Iris-versicolor']
 [7.2 3.6 6.1 2.5 'Iris-virginica']
 [5.7 2.9 4.2 1.3 'Iris-versicolor']
 [7.6 3.0 6.6 2.1 'Iris-virginica']
 [5.6 3.0 4.5 1.5 'Iris-versicolor']
 [5.1 3.5 1.4 0.2 'Iris-setosa']
 [7.7 2.8 6.7 2.0 'Iris-virginica']
 [5.8 2.7 4.1 1.0 'Iris-versicolor']
 [5.2 3.4 1.4 0.2 'Iris-setosa']
 [5.0 3.5 1.3 0.3 'Iris-setosa']
 [

In [43]:
# Preprocessing
data = []
for data in X_train:
    if data[4] == "Iris-setosa":
        X_train[4] = 0
    elif data[4] == "Iris-versicolor":
        X_train[4] = 1
    else:
        X_train[4] = 2
    print (X_train)

[[4.6 3.6 1.0 0.2 0]
 [5.7 4.4 1.5 0.4 0]
 [6.7 3.1 4.4 1.4 1]
 [4.8 3.4 1.6 0.2 0]
 [2 2 2 2 2]
 [6.3 2.5 5.0 1.9 2]
 [6.4 3.2 4.5 1.5 1]
 [5.2 3.5 1.5 0.2 0]
 [5.0 3.6 1.4 0.2 0]
 [5.2 4.1 1.5 0.1 0]
 [5.8 2.7 5.1 1.9 2]
 [6.0 3.4 4.5 1.6 1]
 [6.7 3.1 4.7 1.5 1]
 [5.4 3.9 1.3 0.4 0]
 [5.4 3.7 1.5 0.2 0]
 [5.5 2.4 3.7 1.0 1]
 [6.3 2.8 5.1 1.5 2]
 [6.4 3.1 5.5 1.8 2]
 [6.6 3.0 4.4 1.4 1]
 [7.2 3.6 6.1 2.5 2]
 [5.7 2.9 4.2 1.3 1]
 [7.6 3.0 6.6 2.1 2]
 [5.6 3.0 4.5 1.5 1]
 [5.1 3.5 1.4 0.2 0]
 [7.7 2.8 6.7 2.0 2]
 [5.8 2.7 4.1 1.0 1]
 [5.2 3.4 1.4 0.2 0]
 [5.0 3.5 1.3 0.3 0]
 [5.1 3.8 1.9 0.4 0]
 [5.0 2.0 3.5 1.0 1]
 [6.3 2.7 4.9 1.8 2]
 [4.8 3.4 1.9 0.2 0]
 [5.0 3.0 1.6 0.2 0]
 [5.1 3.3 1.7 0.5 0]
 [5.6 2.7 4.2 1.3 1]
 [5.1 3.4 1.5 0.2 0]
 [5.7 3.0 4.2 1.2 1]
 [7.7 3.8 6.7 2.2 2]
 [4.6 3.2 1.4 0.2 0]
 [6.2 2.9 4.3 1.3 1]
 [5.7 2.5 5.0 2.0 2]
 [5.5 4.2 1.4 0.2 0]
 [6.0 3.0 4.8 1.8 2]
 [5.8 2.7 5.1 1.9 2]
 [6.0 2.2 4.0 1.0 1]
 [5.4 3.0 4.5 1.5 1]
 [6.2 3.4 5.4 2.3 2]
 [5.5 2.3 4.0 1.3 1]


 [7.1 3.0 5.9 2.1 2]]
[[4.6 3.6 1.0 0.2 0]
 [5.7 4.4 1.5 0.4 0]
 [6.7 3.1 4.4 1.4 1]
 [4.8 3.4 1.6 0.2 0]
 [2 2 2 2 2]
 [6.3 2.5 5.0 1.9 2]
 [6.4 3.2 4.5 1.5 1]
 [5.2 3.5 1.5 0.2 0]
 [5.0 3.6 1.4 0.2 0]
 [5.2 4.1 1.5 0.1 0]
 [5.8 2.7 5.1 1.9 2]
 [6.0 3.4 4.5 1.6 1]
 [6.7 3.1 4.7 1.5 1]
 [5.4 3.9 1.3 0.4 0]
 [5.4 3.7 1.5 0.2 0]
 [5.5 2.4 3.7 1.0 1]
 [6.3 2.8 5.1 1.5 2]
 [6.4 3.1 5.5 1.8 2]
 [6.6 3.0 4.4 1.4 1]
 [7.2 3.6 6.1 2.5 2]
 [5.7 2.9 4.2 1.3 1]
 [7.6 3.0 6.6 2.1 2]
 [5.6 3.0 4.5 1.5 1]
 [5.1 3.5 1.4 0.2 0]
 [7.7 2.8 6.7 2.0 2]
 [5.8 2.7 4.1 1.0 1]
 [5.2 3.4 1.4 0.2 0]
 [5.0 3.5 1.3 0.3 0]
 [5.1 3.8 1.9 0.4 0]
 [5.0 2.0 3.5 1.0 1]
 [6.3 2.7 4.9 1.8 2]
 [4.8 3.4 1.9 0.2 0]
 [5.0 3.0 1.6 0.2 0]
 [5.1 3.3 1.7 0.5 0]
 [5.6 2.7 4.2 1.3 1]
 [5.1 3.4 1.5 0.2 0]
 [5.7 3.0 4.2 1.2 1]
 [7.7 3.8 6.7 2.2 2]
 [4.6 3.2 1.4 0.2 0]
 [6.2 2.9 4.3 1.3 1]
 [5.7 2.5 5.0 2.0 2]
 [5.5 4.2 1.4 0.2 0]
 [6.0 3.0 4.8 1.8 2]
 [5.8 2.7 5.1 1.9 2]
 [6.0 2.2 4.0 1.0 1]
 [5.4 3.0 4.5 1.5 1]
 [6.2 3.4 5.4 2.3 2]

In [47]:
def euclidean_dist(x1,x2):
    euc_dist = 0
    for ind in range(len(x1)):
        sq_dist = pow((x1[ind]-x2[ind]),2)
        euc_dist = euc_dist + sq_dist
    return (math.sqrt(euc_dist))

In [48]:
def nearest_neighbors(x_train, x_test, k):
    distances = []
    neighbors = []
    for train_row in x_train:
        distances.append((train_row, euclidean_dist(train_row, x_test)))
    distances.sort(key = lambda tup: tup[1])
    top_k = distances[0:k]
    return top_k

In [49]:
def knn_predict(x_train, x_test, k):
    neighbors = nearest_neighbors(x_train, x_test, k)
    top_neighbors = [x[-1] for x in neighbors]
    pred_outcome = max(set(top_neighbors), key=top_neighbors.count)
    return pred_outcome

In [50]:
test = X_train[1]
# print(test)
knn_predict(X_train, test, 3)

0.0